In [57]:
import numpy as np
from scipy.stats import special_ortho_group
np.set_printoptions(suppress = True, precision = 4)

p1 = [[1, 2, 3   ],
      [4, 5, 6   ],
      [7, 8, 9   ],
      [10, 11, 12],
      [13, 14, 15],
      [16, 17, 18],
      [19, 20, 21],
      [22, 23, 24],
      [25, 26, 27],
      [28, 29, 30],
      [31, 32, 33],
      [34, 35, 36]]
#p1 = p1[:6]
p1 = np.array(p1).T
R = special_ortho_group.rvs(3)
T = np.zeros((3,1)) * 10
p2 = R.dot(p1) + T

In [61]:
def get_A(p1, p2):
    n = p1.shape[1]
    A = np.zeros((3 * n, 12))
    for i in range(n):
        p1_i = p1[:,i]
        p2_i = p2[:,i]
        
        x1 = p1_i[0]
        y1 = p1_i[1]
        z1 = p1_i[2]
        x2 = p2_i[0]
        y2 = p2_i[1]
        z2 = p2_i[2]
        
        a1 = [0       , 0       , 0       , -z2* x1, -z2*y1 , -z2 *z1, y2 * x1, y2 * y1 , y2 * z1, 0  , -z2, y2  ]
        a2 = [z2* x1  , z2*y1   , z2*z1   , 0      , 0      , 0      , -x2*x1 , -x2 * y1, -x2* z1, z2 , 0  , -x2 ]
        a3 = [-y2 * x1, -y2 * y1, -y2 * z1, x2 * x1, x2 * y1, x2 * z1, 0      ,   0     ,  0     , -y2, x2 , 0   ]
        a1 = np.array(a1)
        a2 = np.array(a2)
        a3 = np.array(a3)
        A[i*3 + 0, :] = a1
        A[i*3 + 1, :] = a2
        A[i*3 + 2, :] = a3
    return A

def solve(A):
    u, s, vh = np.linalg.svd(A, full_matrices=True)
    v = vh.T
    last_col_of_v = v[:, -1]
    R = last_col_of_v[:9].reshape((3,3))
    T = last_col_of_v[9:12].reshape((3,1))
    return R, T

In [62]:
A = get_A(p1, p2)
R_est, T_est = solve(A)
print "R_gt"
print R
print "R_est"
print R_est

print "t_gt"
print T
print "t_est"
print T_est

p_2 = R_est.dot(p1) + T_est
print np.sum(np.abs(p_2 - p2))

R_gt
[[ 0.8399  0.3627  0.4038]
 [ 0.5381 -0.6536 -0.5321]
 [ 0.0709  0.6642 -0.7442]]
R_est
[[ 0.4743 -0.6778  0.0609]
 [ 0.1676 -0.1431  0.033 ]
 [ 0.0036 -0.0069  0.0041]]
t_gt
[[0.]
 [0.]
 [0.]]
t_est
[[0.4521]
 [0.2296]
 [0.0719]]
565.9427397247459
